baseurl = "https://soundathletics.org/"
languageCode = "en-us"
title = "Sound Athletics"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
theme = "hugo-minimalist"

[markup]
  defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
  unsafe = true

[params]
    site_author = "Sound Athletics"
    site_description = "The awesome website of Sound Athletics."
    location = "Pierce County Washington"
    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "img/soundathleticsavatar.jpg"
    header_background = "img/soundathleticscover.jpg"
    header_title = "Sound Athletics"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    main_menu = ["calendar", "athlete signup", "sports", "donations", "about sa"]
    footer_menu = ["calendar", "athlete signup", "sports", "volunteer today", "coaching opportunities", "about sa"]

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = "SoundAthletics"
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = ""
    gplus     = ""
